algoritmo "semnome"

var

  x1, x2, x3, x4: real

inicio

     Escreval ("Qual a altura da parede em metros que se deseja pintar?")
     Leia (x1)
     Escreval ("E a largura dessa mesma parede em metros?")
     Leia (x2)
     x3 <- (x1*x2)
     x4 <- (x3/2)
     Escreval ("A área da parede é igual a", x3," metros quadrados.")
     Escreval ("Logo, serão necessários",x4," litros de tinta para pintar toda a parede.")


     
     

fimalgoritmo
