algoritmo "semnome"

var

      c: inteiro

inicio

                  c <- 30
                  Enquanto (c>=1) faca
                     Se (c%4=0) entao
                        Escreva (" [",c," ]")
                        c <- (c-1)
                     Senao
                        Escreva (c)
                        c <- (c-1)
                     FimSe
                  FimEnquanto

fimalgoritmo
